Updated functionality for data generation - initialize docker/ singularity and generate data using a config file

diff --git a/src/data_generation/docker/Dockerfile b/src/data_generation/docker/Dockerfile
--- a/src/data_generation/docker/Dockerfile
+++ b/src/data_generation/docker/Dockerfile
@@ -14,8 +14,10 @@ RUN wget https://github.com/conda-forge/miniforge/releases/download/23.1.0-2/Mam
     rm Mambaforge-Linux-x86_64.sh
 ENV PATH=/opt/mambaforge/bin:$PATH
 
-# Clone the NeuroMotion repo
-RUN git clone https://github.com/pranavm19/NeuroMotion
+# Clone the NeuroMotion repo with specific version
+RUN git clone https://github.com/shihan-ma/NeuroMotion.git && \
+    cd NeuroMotion && \
+    git checkout 590369ec2f395e6e228aa9dc58bf0fb87a2c0329
 
 # Switch to repo directory
 WORKDIR /opt/NeuroMotion
@@ -30,10 +32,26 @@ RUN mamba run -n NeuroMotion pip install \
     git+https://github.com/shihan-ma/BioMime.git \
     gdown
 
-RUN mamba run -n NeuroMotion bash get_data.sh
+# Create directories with proper permissions
+RUN mkdir -p ckp && \
+    mkdir -p NeuroMotion/MSKlib/models
 
-# Activate env by default
-# ENV CONDA_DEFAULT_ENV=NeuroMotion
-# ENV PATH=/opt/mambaforge/envs/NeuroMotion/bin:$PATH
+# Download the files using gdown with error checking
+RUN mamba run -n NeuroMotion bash -c '\
+    for url in "1RIYnYxLkBZ9_7MJQgQBSjAk_oXBTqY0b" "1xxeXF4RS7qH-kq3yrfCiWIQ7DemMounr" "10PoLwJcHoS8ZRvqlExENpt3tt2Vus72s" "1HD3UQFgaxSTsZIFW04bp-pLmn8UROBEp"; do \
+        if ! gdown $url; then \
+            echo "Failed to download file for URL: $url" && exit 1; \
+        fi \
+    done'
+
+RUN mamba run -n NeuroMotion bash -c '\
+    gdown 1RIYnYxLkBZ9_7MJQgQBSjAk_oXBTqY0b -O ckp/model_linear.pth && \
+    gdown 1xxeXF4RS7qH-kq3yrfCiWIQ7DemMounr -O ckp/muap_example.pkl && \
+    gdown 10PoLwJcHoS8ZRvqlExENpt3tt2Vus72s -O NeuroMotion/MSKlib/models/poses.csv && \
+    gdown 1HD3UQFgaxSTsZIFW04bp-pLmn8UROBEp -O NeuroMotion/MSKlib/models/ARMS_Wrist_Hand_Model_4.3.zip'
+
+RUN unzip NeuroMotion/MSKlib/models/ARMS_Wrist_Hand_Model_4.3.zip -d NeuroMotion/MSKlib/models/ && \
+    rm NeuroMotion/MSKlib/models/ARMS_Wrist_Hand_Model_4.3.zip
+
 
 CMD ["/bin/bash"]
